include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas

    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_final_fields
    - prefer_single_quotes
    - avoid_redundant_argument_values
    - always_put_control_body_on_new_line
    - always_require_non_null_named_parameters
    - annotate_overrides
    - no_duplicate_case_values
    - prefer_is_empty
    - unnecessary_this
    - use_key_in_widget_constructors
